---
- name: Execute Compliance Tasks
  hosts: "{{ target_host }}"
  tasks:
    - import_playbook: compliance-audit/roles/ansible_motd/tasks/main.yaml
    - import_playbook: compliance-audit/roles/ansible_ntp/tasks/main.yml
    - import_playbook: compliance-audit/roles/ansible_passwd/tasks/main.yml
