# ---
# - hosts: target_vm
#   tasks:
#     - name: Execute motd role
#       import_role:
#         name: compliance-audit/roles/ansible_motd  # Update with the correct path to your role

#     - name: Execute ntp role
#       import_role:
#         name: compliance-audit/roles/ansible_ntp  # Update with the correct path to your role
        
#     - name: Execute passwd role
#       import_role:
#         name: compliance-audit/roles/ansible_passwd  # Update with the correct path to your role

   
#     - name: Fetch motd role outputs file from target VM
#       fetch:
#         src: "/tmp/ansible_motd/role_outputs.yml"
#         dest: "/tmp/ansible_motd/role_outputs.yml"
#         flat: yes
    
#     - name: Fetch ntp role outputs file from target VM
#       fetch:
#         src: "/tmp/ansible_ntp/role_outputs.yml"
#         dest: "/tmp/ansible_ntp/role_outputs.yml"
#         flat: yes
    
#     - name: Fetch passwd role outputs file from target VM
#       fetch:
#         src: "/tmp/ansible_passwd/role_outputs.yml"
#         dest: "/tmp/ansible_passwd/role_outputs.yml"
#         flat: yes


#     - name: Include role outputs
#       include_vars:
#         file: "/tmp/role_outputs.yml"

#     - name: Display role execution results
#       debug:
#         var: files_list.stderr

#     - debug:
#         var: path.stderr

#     - debug:
#         var: osname.stderr




---
- hosts: target_vm
  tasks:
    - name: Execute motd role
      import_role:
        name: compliance-audit/roles/ansible_motd

    - name: Execute ntp role
      import_role:
        name: compliance-audit/roles/ansible_ntp

    - name: Execute passwd role
      import_role:
        name: compliance-audit/roles/ansible_passwd
        
    # - name: Fetch motd role outputs file from target VM
    #   fetch:
    #     src: "/tmp/ansible_motd/role_outputs.yml"
    #     dest: "/tmp/ansible_motd/role_outputs.yml"
    #     flat: yes
    
    # - name: Fetch ntp role outputs file from target VM
    #   fetch:
    #     src: "/tmp/ansible_ntp/role_outputs.yml"
    #     dest: "/tmp/ansible_ntp/role_outputs.yml"
    #     flat: yes
    
    # - name: Fetch passwd role outputs file from target VM
    #   fetch:
    #     src: "/tmp/ansible_passwd.yml"
    #     dest: "/tmp/ansible_passwd.yml"
    #     flat: yes

    # - name: Include role outputs
    #   include_vars:
    #     file: "/tmp/ansible_passwd.yml"
    
    - name: Display failure reason if any role block failed in motd role
      debug:
        msg: "{{ motd_failure_reason }}"
      when: role_failed | default(false)


    - name: Display failure reason if any role block failed in ntp role
      debug:
        msg: "{{ ntp_failure_reason }}"
      when: role_failed | default(false)
    
    - name: Display failure reason if any role block failed in passwd role
      debug:
        msg: "{{ passwd_failure_reason }}"
      when: role_failed | default(false)

