---
- hosts: localhost
  tasks:
    - name: Execute ntp role
      import_role:
        name: roles/ntp/tasks
    - name: Display ntp_compliant result
      debug:
        msg: ntp_compliant is {{ ntp_audit_ntp }}
    - name: Display compliance results in json
      debug:
        msg: |
          {
            "host_compliant": {{ (ntp_audit_ntp.compliant) | lower }},
            "cmcp_audit_ntp": {{ ntp_audit_ntp }}
          }
