---
- hosts: target_vm
  tasks:
    - name: Execute motd role
      import_role:
        name: compliance-audit/roles/ansible_motd

    - name: Display motd_compliant result
      debug:
        msg: "motd_compliant is {{ motd_audit_ntp }}"
