# ---
# - name: List files using shell command
#   shell: ls -la
#   register: files_list
#   ignore_errors: true
  
# - name: List path using shell command
#   shell: pwd
#   register: path
#   ignore_errors: true

# - name: List osname using shell command
#   shell: uname
#   register: osname
#   ignore_errors: true
  
# - name: Store task outputs in a file
#   copy:
#     content: |
#       files_list: "{{ files_list.stdout_lines }}"
#       path: "{{ path.stdout }}"
#       osname: "{{ osname.stdout }}"
#     dest: "/tmp/ansible_passwd/role_outputs.yml"


---
- name: List files using shell command
  shell: "echo 'This is a test command'"
  register: files_list
  ignore_errors: true
  
- name: List path using shell command
  shell: pwd
  register: path
  ignore_errors: true

- name: List osname using shell command
  shell: unameehbiebe
  register: osname
  ignore_errors: true

- name: return compliance result
  set_fact:
    passwd_audit_ntp: "{ 'compliant': {{ ( false if (files_list.changed) else true ) }} }"

- ansible.builtin.debug:
    var: passwd_audit_ntp
