# ---
# - name: List files using shell command
#   shell: ls -la
#   register: files_list
#   ignore_errors: true
  
# - name: List path using shell command
#   shell: pwd
#   register: path
#   ignore_errors: true

# - name: List osname using shell command
#   shell: unameeeee
#   register: osname
#   ignore_errors: true
  
# - name: Store task outputs in a file
#   copy:
#     content: |
#       files_list: "{{ files_list.stdout_lines }}"
#       path: "{{ path.stdout }}"
#       osname: "{{ osname.stdout }}"
#     dest: "/tmp/ansible_passwd/role_outputs.yml"


---
- name: List files using shell command
  shell: ls -la
  register: files_list
  ignore_errors: true
  
- name: List path using shell command
  shell: pwd
  register: path
  ignore_errors: true

- name: List osname using shell command
  shell: unameeeee
  register: osname
  ignore_errors: true

- name: Set error fact if any command failed
  set_fact:
    role_failed: true
    failure_reason: >-
      {{ files_list.stderr if files_list.failed else '' }}
      {{ path.stderr if path.failed else '' }}
      {{ osname.stderr if osname.failed else '' }}

- name: Store task outputs in a file
  copy:
    content: |
      files_list: "{{ files_list.stdout_lines }}"
      path: "{{ path.stdout }}"
      osname: "{{ osname.stdout }}"
      failure_reason: "{{ failure_reason }}"
    dest: "/tmp/ansible_passwd.yml"
