---
- name: List files using shell command
  shell: date
  register: files_list
  ignore_errors: true
  
- name: List path using shell command
  shell: pwd
  register: path
  ignore_errors: true

- name: List osname using shell command
  shell: uname
  register: osname
  ignore_errors: true
  
- name: summarise item compliance
  set_fact:
    motd_compliant: "{{ false if (files_list.changed) else true }}"

- name: return compliance result
  set_fact:
    motd_audit_ntp: "{ 'compliant': {{ ( false if (files_list.changed) else true ) }} }"

- ansible.builtin.debug:
    var: motd_audit_ntp
