---
- name: List files using shell command
  shell: ls -la
  register: files_list
  ignore_errors: true
  
- name: List path using shell command
  shell: pwd
  register: path
  ignore_errors: true

- name: List osname using shell command
  shell: uname
  register: osname
  ignore_errors: true
  
- name: return compliance result
  set_fact:
    ntp_audit_ntp: "{ 'compliant': {{ ( false if (files_list.changed) else true ) }} }"

- ansible.builtin.debug:
    var: ntp_audit_ntp

# ---
# - name: List files using shell command
#   shell: ls -la
#   register: files_list
#   ignore_errors: true
  
# - name: List path using shell command
#   shell: pwdsss
#   register: path
#   ignore_errors: true

# - name: List osname using shell command
#   shell: uname
#   register: osname
#   ignore_errors: true
  
# - name: Set error fact if any command failed
#   set_fact:
#     role_failed: true
#     ntp_failure_reason: >-
#       {%- set error_msgs = [] -%}
#       {%- if files_list.failed -%}
#       {%- set _ = error_msgs.append("- List files using shell command failed.") -%}
#       {{ files_list.stderr }}
#       {%- endif -%}
#       {%- if path.failed -%}
#       {%- set _ = error_msgs.append("- List path using shell command failed.") -%}
#       {{ path.stderr }}
#       {%- endif -%}
#       {%- if osname.failed -%}
#       {%- set _ = error_msgs.append("- List osname using shell command failed.") -%}
#       {{ osname.stderr }}
#       {%- endif -%}
#       {%- if error_msgs %}
#       {{ error_msgs | join('\n') }}
#       {%- else %}
#       "All commands executed successfully."
#       {%- endif %}
