---
- name: List files using shell command
  shell:
    cmd: ls -la  
  register: files_list

- name: List files using shell command
  shell:
    cmd: pwd  
  register: path
  
- name: List files using shell command
  shell:
    cmd: uname  
  register: osname

